### ISSUE TITLE
Support for `.relatedTo`

### ISSUE THREAD

**Issue by dsmrt** [flipboxfactory/craft-element-lists#4]
I was just querying relations via twig and was having issues with the `relatedTo` working. I ended up using `where` which is much more straight forward. Not a big deal for me but I'd assume others would want to use it.

**Comment by nateiler** [comment]
Behind the scenes, as of v2, we're storing the relations in the same 'relations' table that Craft uses.  As a result, the `relatedTo` should work.  In addition, you should be able to switch between the native relations field type(s) and element list(s).
